---
title: "Replication of Simulations in Bach et al. (2020) - DoubleML - An Object-Oriented Implementation of Double Machine Learning in R"
author: "Philipp Bach"
date: "`r format(Sys.Date(), format='%b %d, %Y')`"
output: github_document
---

In this repository, we list and automatically run the simulation examples presented in [Bach et al. (2020)](https://arxiv.org/abs/2103.09603)


## Files for Replication of Figures and Results in DoubleML Package Vignette

The examples and results from the paper *DoubleML - An Object-Oriented Implementation of Double Machine Learning in R* can be reproduced with the R files listed in the following: 

1. Section 4: *Basic idea and key ingredients of double machine learning* - Code for replication of simulation examples
    + `examples_failure_n_500_p_20.R`
2. Section 7.8: *A short simulation study* - Code for replication of simulation results
    + Cross-fitting: `examples_failure_n_500_p_20.R`
    + PLR: `sim_plr.R`
    + PLIV: `sim_plivX.R`
    + IRM: `sim_irm.R`
    + IIVM: `sim_IIVM.R`
    + Merging plots: `merge_plots.R`
    + Simultaneous inference: `sim_siminf.R`
3. Code chunks: The reproducible code contained in the code chunks is available via
    + `doubleml_codechunks.R`

All data sets and DGPs used in the paper can be via corresponding functions as provided in the `DoubleML` package. The required function calls are contained in the code chunks of the paper. The API documentation is available via https://docs.doubleml.org/r/stable/reference/index.html. 

The current development version of `DoubleML` is available via the GitHub repository at https://github.com/DoubleML/doubleml-for-r. The stable version can be downloaded from CRAN https://cran.r-project.org/web/packages/DoubleML/index.html.

In case you have any questions, do not hesitate to contact philipp.bach@uni-hamburg.de 

## Citation

If you use the DoubleML package a citation is highly appreciated:

Bach, P., Chernozhukov, V., Kurz, M. S., and Spindler, M. (2021), DoubleML - An Object-Oriented Implementation of Double Machine Learning in Python, arXiv:2104.03220.

```
@misc{DoubleML2021R,
  title={{DoubleML} -- {A}n Object-Oriented Implementation of Double Machine Learning in {R}},
  author={P. Bach and V. Chernozhukov and M. S. Kurz and M. Spindler},
  year={2021},
  eprint={2103.09603},
  archivePrefix={arXiv},
  primaryClass={stat.ML},
  note={arXiv:\href{https://arxiv.org/abs/2103.09603}{2103.09603} [stat.ML]}
}
```

## References

Bach, P., Chernozhukov, V., Kurz, M. S., and Spindler, M. (2021), DoubleML - An Object-Oriented Implementation of Double Machine Learning in Python, arXiv:2104.03220.
