# Workflow based on https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/
name: Replication

on:
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  replicate-simulation:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }}; mlr3 ${{ matrix.config.mlr3 }}; DoubleML ${{ matrix.config.DoubleML }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', mlr3: 'release', DoubleML: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-${{ matrix.config.mlr3 }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-${{ matrix.config.mlr3 }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Introduction and Cross Fit
        run: |
          source("R/examples_failure_n_500_p_20.R")
        shell: Rscript {0}

      - name: Run PLR
        run: |
          source("R/sim_plr.R")
        shell: Rscript {0}

      - name: Run PLIV
        run: |
          source("R/sim_plivX.R")
        shell: Rscript {0}

      - name: Run IRM
        run: |
          source("R/sim_irm.R")
        shell: Rscript {0}

      - name: Run IIVM
        run: |
          source("R/sim_iivm.R")
        shell: Rscript {0}

      - name: Run SimInf
        run: |
          source("R/sim_siminf.R")
        shell: Rscript {0}

      - name: Merge PLR, PLIV, IRM, IIVM
        run: |
          source("R/merge_plots.R")
        shell: Rscript {0}
